### PR TITLE
fix user dict tag bug : wrong buf index assigned

### PR DESCRIPTION
**Pull request by bigelephant29**
I tried to load my own dictionary and found that the tag strings were always wrong.

After tracing some files, I found the index assigned for tag buf were wrong.

### CODE REVIEW

**Comment by bigelephant29** [comment]
I found that the structure of user dict is different from jieba dict.

Should cppjieba support user-defined weight and tag?

I think the current version allows user-defined tag only.

**Comment by yanyiwu** [comment]
your pr only support user tag, not for user weight?and please pass all the test

**Comment by bigelephant29** [comment]
Hi, 
I have passed all the test.
I think the current version can support both my dictionary and the user dict in this repo.
This is my first pr, sorry for any inconvenience.

Please contact me if I made any mistake, thanks a lot.

**Comment by yanyiwu** [comment]
Thank you so much!

**Pull request merged**
